"""Add pin coumn

Revision ID: 0436cd4635ee
Revises: f5c406467870
Create Date: 2025-12-20 23:36:54.071376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0436cd4635ee'
down_revision: Union[str, Sequence[str], None] = 'f5c406467870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('pin', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'pin')
    # ### end Alembic commands ###
