"""Add extra columns

Revision ID: 0e01e6027bde
Revises: d602e29a2bb2
Create Date: 2026-01-12 20:46:25.764435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e01e6027bde'
down_revision: Union[str, Sequence[str], None] = 'd602e29a2bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('third_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('jshir', sa.String(), nullable=True))
    op.add_column('users', sa.Column('passport_series', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passport_series')
    op.drop_column('users', 'jshir')
    op.drop_column('users', 'third_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
