"""Add subject table

Revision ID: 216e5d8ed98c
Revises: f11fa4583b32
Create Date: 2025-12-20 12:06:02.007134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216e5d8ed98c'
down_revision: Union[str, Sequence[str], None] = 'f11fa4583b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('questions', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'questions', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.add_column('quizzes', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'quizzes', ['subject_id'])
    op.create_foreign_key(None, 'quizzes', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', type_='unique')
    op.drop_column('quizzes', 'subject_id')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'subject_id')
    op.drop_table('subjects')
    # ### end Alembic commands ###
