"""Add user id to subject

Revision ID: 71ea5727127b
Revises: 216e5d8ed98c
Create Date: 2025-12-20 21:25:21.670825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ea5727127b'
down_revision: Union[str, Sequence[str], None] = '216e5d8ed98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_subjects_user_id'), 'subjects', ['user_id'], unique=False)
    op.create_foreign_key(None, 'subjects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_index(op.f('ix_subjects_user_id'), table_name='subjects')
    op.drop_column('subjects', 'user_id')
    # ### end Alembic commands ###
