"""Change question

Revision ID: f11fa4583b32
Revises: c1c4aedfc359
Create Date: 2025-12-19 12:52:43.539903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f11fa4583b32'
down_revision: Union[str, Sequence[str], None] = 'c1c4aedfc359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_questions_user_id'), 'questions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('questions', 'correct_option')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('correct_option', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_user_id'), table_name='questions')
    op.drop_column('questions', 'user_id')
    # ### end Alembic commands ###
