"""Delete subject

Revision ID: f5c406467870
Revises: 71ea5727127b
Create Date: 2025-12-20 23:11:59.593147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5c406467870'
down_revision: Union[str, Sequence[str], None] = '71ea5727127b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key constraints FIRST
    op.drop_constraint(op.f('questions_subject_id_fkey'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('quizzes_subject_id_fkey'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('quizzes_subject_id_key'), 'quizzes', type_='unique')
    
    # Now drop the subjects table and its index
    op.drop_index(op.f('ix_subjects_user_id'), table_name='subjects')
    op.drop_table('subjects')
    
    # Drop the old association table
    op.drop_index(op.f('ix_quiz_question_association_question_id'), table_name='quiz_question_association')
    op.drop_index(op.f('ix_quiz_question_association_quiz_id'), table_name='quiz_question_association')
    op.drop_table('quiz_question_association')
    
    # Add new quiz_id column to questions and create the new relationship
    op.add_column('questions', sa.Column('quiz_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_questions_quiz_id'), 'questions', ['quiz_id'], unique=False)
    op.create_foreign_key(None, 'questions', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    
    # Remove old subject_id column from questions
    op.drop_column('questions', 'subject_id')
    
    # Remove old subject_id column from quizzes
    op.drop_column('quizzes', 'subject_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('quizzes_subject_id_fkey'), 'quizzes', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('quizzes_subject_id_key'), 'quizzes', ['subject_id'], postgresql_nulls_not_distinct=False)
    op.add_column('questions', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_subject_id_fkey'), 'questions', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_questions_quiz_id'), table_name='questions')
    op.drop_column('questions', 'quiz_id')
    op.create_table('quiz_question_association',
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('quiz_question_association_question_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('quiz_question_association_quiz_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_question_association_pkey')),
    sa.UniqueConstraint('quiz_id', 'question_id', name=op.f('uq_quiz_question'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_quiz_question_association_quiz_id'), 'quiz_question_association', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_question_association_question_id'), 'quiz_question_association', ['question_id'], unique=False)
    op.create_table('subjects',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('subjects_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('subjects_pkey'))
    )
    op.create_index(op.f('ix_subjects_user_id'), 'subjects', ['user_id'], unique=False)
    # ### end Alembic commands ###